//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the AI Name Map Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace UtilityAI
{
    using System;

    public static class AINameMapHelper
    {
		public static readonly Guid AgentActionAI = new Guid("f855880b30b304fd7869bfcc538938bb");
		public static readonly Guid AgentMoveAI = new Guid("b6a23c75e462441e596a1decd1020bb9");
		public static readonly Guid AgentScanAI = new Guid("b35eb05201aee4bb8892cb8a8d34fa60");

    }
}
