//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the AI Name Map Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace UtilityAI
{
    using System;

    public static class AINameMapHelper
    {
		public static readonly Guid AgentActionAI = new Guid("0ef02b0031ce5417abd2f84b8cea1ff7");
		public static readonly Guid AgentMoveAI = new Guid("8d75d33343c884e7f8ca31ed81afd3c6");
		public static readonly Guid AgentScanAI = new Guid("db35650a0b2464340a69d3d5ea3381a5");

    }
}
