//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the AI Name Map Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace uUtilityAI
{
    using System;

    public static class AINameMap
    {
		public static readonly Guid GenericAI = new Guid("ef56ca58443c644eabfcfb34e2da8f00");

    }
}
