//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the AI Name Map Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace UtilityAI
{
    using System;

    public static class AINameMapHelper
    {
		public static readonly Guid AgentActionAI = new Guid("c5a766a5ce1da4fbd82b13c3b2b4505c");
		public static readonly Guid AgentMoveAI = new Guid("86b9f24b0a74541d7bd83ae917f93123");
		public static readonly Guid AgentScanAI = new Guid("a3f5b4b22cf4a4b669d56c84d12779ab");

    }
}
